name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/vector.png
  - assets/images/pngfuel_11.png
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/battery_1_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/cellular_connection_1_x2.svg
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/images/pngfuel_9.png
  - assets/images/pngfuel_61.png
  - assets/images/pngfuel_62.png
  - assets/images/pngfuel_7.png
  - assets/images/pngfuel.png
  - assets/images/pngfuel_8.png
  - assets/images/pngfuel_6.png
  - assets/vectors/wifi_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/cellular_connection_x2.svg
  - assets/vectors/group_11_x2.svg
  - assets/vectors/battery_x2.svg
  - assets/vectors/vector_12_x2.svg

